project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('quality_control/', include('quality_control.urls')),
    path('tasks/', include('tasks.urls')), 
]

quality_control/urls.py
from django.urls import path, include
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('bug/', views.bug_list, name='bug_list'),  # новый маршрут
    path('bug/<int:bugreport_id>/', views.bugreport_detail, name='bugreport_detail'),
    path('feature/', views.feature_list, name='feature_list'),
    path('feature/<int:featurerequest_id>/', views.featurerequest_detail, name='featurerequest_detail'),
    path('bug/new/', views.create_bugreport, name='create_bugreport'),
    path('feature/new/', views.create_featurerequest, name='create_featurerequest'),
    path('bug/<int:bugreport_id>/update/', views.update_bugreport, name='update_bugreport'),
    path('feature/<int:featurerequest_id>/update/', views.update_featurerequest, name='update_featurerequest'),
    path('bug/<int:bugreport_id>/delete/', views.delete_bugreport, name='delete_bugreport'),
    path('feature/<int:featurerequest_id>/delete/', views.delete_featurerequest, name='delete_featurerequest'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('bug/', views.BugListView.as_view(), name='bug_list'),
    # path('bug/<int:bugreport_id>/', views.BugDetailView.as_view(), name='bugreport_detail'),
    # path('feature/', views.FeatureListView.as_view(), name='feature_list'),
    # path('feature/<int:featurerequest_id>/', views.FeatureDetailView.as_view(), name='featurerequest_detail'),
    # path('bug/<int:bugreport_id>/delete/', views.BugReportDeleteView.as_view(), name='delete_bugreport'),
    # path('feature/<int:featurerequest_id>/delete/', views.FeatureRequestDeleteView.as_view(), name='delete_featurerequest'),
    # path('bug/<int:bugreport_id>/update/', views.BugReportUpdateView.as_view(), name='update_bugreport'),
    # path('feature/<int:featurerequest_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_featurerequest'),
    # path('bug/new/', views.BugReportCreateView.as_view(), name='create_bugreport'),
    # path('feature/new/', views.FeatureRequestCreateView.as_view(), name='create_featurerequest'),
]

tasks/urls.py
from django.urls import path, include
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('another/', views.another_page, name='another_page'),  # новый маршрут
    path('quality_control/', include('quality_control.urls'), name = 'quality'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('feedback/', views.feedback_view, name='feedback'),
    # path('project/new/', views.create_project, name='create_project'),
    # path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/new/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
]

quality_control/models.py
from django.db import models
from tasks.models import Project
from tasks.models import Task

class BugReport(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    PRIORITY_CHOICES = [
        ('New', 'Важно'),
        ('In_progress', 'Можно отложить'),
        ('Completed', 'Надо сделать'),
    ]
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='bugreport',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='bugreport',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    
    
    priority = models.CharField(
        max_length=50,
        choices=PRIORITY_CHOICES,
        default='Важно',
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
class FeatureRequest(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    PRIORITY_CHOICES = [
        ('New', 'Важно'),
        ('In_progress', 'Можно отложить'),
        ('Completed', 'Надо сделать'),
    ]
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='featurerequest',
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='featurerequest',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    
    
    priority = models.CharField(
        max_length=50,
        choices=PRIORITY_CHOICES,
        default='Важно',
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )

quality_control/forms.py
from django.forms import ModelForm
from .models import BugReport

class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description','status','project','task','priority']

from .models import FeatureRequest

class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description','status','project','task','priority']

quality_control/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404
from .models import FeatureRequest, BugReport
from django.shortcuts import render
from django.shortcuts import render, redirect
from .forms import BugReportForm
from .forms import FeatureRequestForm
from django.views.generic import View
from django.views.generic import ListView
from django.views.generic import DetailView






def index(request):
    return render(request, 'quality_control/index.html')

def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bug_list': bugs})



def bugreport_detail(request, bugreport_id):
    bug = get_object_or_404(BugReport, id=bugreport_id)
    return render(request, 'quality_control/bugreport_detail.html', {'bugreport_detail': bug})

def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'feature_list': features})

def featurerequest_detail(request, featurerequest_id):
    feature = get_object_or_404(FeatureRequest, id=featurerequest_id)
    return render(request, 'quality_control/featurerequest_detail.html', {'featurerequest_detail': feature})


def create_bugreport(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})

from .forms import FeatureRequestForm

def create_featurerequest(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})




def update_bugreport(request, bugreport_id):
    bugreport = get_object_or_404(BugReport, pk=bugreport_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bugreport)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugreport_detail', bugreport_id=bugreport.id)
    else:
        form = BugReportForm(instance=bugreport)
    return render(request, 'quality_control/bugreport_update.html', {'form': form, 'bugreport': bugreport})

def update_featurerequest(request, featurerequest_id):
    featurerequest = get_object_or_404(FeatureRequest, pk=featurerequest_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=featurerequest)
        if form.is_valid():
            form.save()
            return redirect('quality_control:featurerequest_detail', featurerequest_id=featurerequest.id)
    else:
        form = FeatureRequestForm(instance=featurerequest)
    return render(request, 'quality_control/featurerequest_update.html', {'form': form, 'featurerequest': featurerequest})

def delete_bugreport(request, bugreport_id):
    bugreport = get_object_or_404(BugReport, pk=bugreport_id)
    bugreport.delete()
    return redirect('quality_control:bug_list')


def delete_featurerequest(request, featurerequest_id):
    featurerequest = get_object_or_404(FeatureRequest, pk=featurerequest_id)
    featurerequest.delete()
    return redirect('quality_control:feature_list')




# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         return render(request, 'quality_control/index.html')


# class BugListView(ListView):
#     model = BugReport
#     template_name = 'quality_control/bug_list.html'
    
# class BugDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bugreport_id'
#     template_name = 'quality_control/bugreport_detail.html'
    
# class FeatureListView(ListView):
#     model = FeatureRequest
#     template_name = 'quality_control/feature_list.html'
    
# class FeatureDetailView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'featurerequest_id'
#     template_name = 'quality_control/featurerequest_detail.html'

# from django.views.generic import CreateView
# from django.urls import reverse, reverse_lazy

# class BugReportCreateView(CreateView):
#     model = BugReport
#     form_class = BugReportForm
#     template_name = 'quality_control/bug_report_form.html'
#     success_url = reverse_lazy('quality_control:bug_list')
    
# class FeatureRequestCreateView(CreateView):
#     model = FeatureRequest
#     form_class = FeatureRequestForm
#     template_name = 'quality_control/featurerequest_create.html'
#     success_url = reverse_lazy('quality_control:feature_list')

# from django.views.generic.edit import UpdateView
# from django.urls import reverse_lazy
# from .models import Project
# from .forms import BugReportForm
# from .forms import FeatureRequestForm

# class BugReportUpdateView(UpdateView):
#     model = BugReport
#     form_class = BugReportForm
#     template_name = 'tasks/bugreport_update.html'
#     pk_url_kwarg = 'bugreport_id'
#     success_url = reverse_lazy('quality_control:bug_list')
    
# class FeatureRequestUpdateView(UpdateView):
#     model = FeatureRequest
#     form_class = FeatureRequestForm
#     template_name = 'tasks/featurerequest_update.html'
#     pk_url_kwarg = 'featurerequest_id'
#     success_url = reverse_lazy('quality_control:feature_list')

# from django.views.generic.edit import DeleteView

# class BugReportDeleteView(DeleteView):
#     model = BugReport
#     pk_url_kwarg = 'bugreport_id'
#     success_url = reverse_lazy('quality_control:bug_list')
#     template_name = 'quality_control/bugreport_confirm_delete.html'

# class FeatureRequestDeleteView(DeleteView):
#     model = FeatureRequest
#     pk_url_kwarg = 'featurerequest_id'
#     success_url = reverse_lazy('quality_control:feature_list')
#     template_name = 'quality_control/featurerequest_confirm_delete.html'

























# def index(request):
#     bugreports_list_url = reverse('quality_control:bug_list')
#     featurerequests_page_url = reverse('quality_control:feature_list')
#     html = f"<h1>Система контроля качества</h1><a href='{bugreports_list_url}'>Список всех багов</a><a href='{featurerequests_page_url}'>Запросы на улучшение</a>"
#     return HttpResponse(html)


# def bug_list(request):
#     bugreports = BugReport.objects.all()
#     bugreports_html = '<h1>Список багов</h1><ul>'
#     for bugreport in bugreports:
#         bugreports_html += f'<li><a href="{bugreport.id}/">{bugreport.title}</a>-{bugreport.status}</a></li>'
#     bugreports_html += '</ul>'
#     return HttpResponse(bugreports_html)

# def feature_list(request):
#     featurerequests = FeatureRequest.objects.all()
#     featurerequests_html = '<h1>Список гениальных идей</h1><ul>'
#     for featurerequest in featurerequests:
#         featurerequests_html += f'<li><a href="{featurerequest.id}/">{featurerequest.title}</a>>{featurerequest.status}</a></li>'
#     featurerequests_html += '</ul>'
#     return HttpResponse(featurerequests_html)

# def bugreport_detail(request, bugreport_id):
#     bugreport = get_object_or_404(BugReport, id=bugreport_id)
#     response_html = f'<h1>{bugreport.title}</h1><p>{bugreport.description}</p>'
#     return HttpResponse(response_html)

# def featurerequest_detail(request, featurerequest_id):
#     featurerequest = get_object_or_404(FeatureRequest, id=featurerequest_id)
#     response_html = f'<h1>{featurerequest.title}</h1><p>{featurerequest.description}</p>'
#     return HttpResponse(response_html)

# from django.views import View

# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         bugreports_list_url = reverse('quality_control:bug_list')
#         featurerequests_page_url = reverse('quality_control:feature_list')
#         html = f"<h1>Система контроля качества</h1><a href='{bugreports_list_url}'>Список всех багов</p><a href='{featurerequests_page_url}'>Запросы на улучшение</a>"
#         return HttpResponse(html)
    
# from django.views.generic import ListView

# class BugListView(ListView):
#     model = BugReport

#     def get(self, request, *args, **kwargs):
#         bugs = self.get_queryset()
#         bugs_html = '<h1>Список багов</h1><ul>'
#         for bugreport in bugs:
#             bugs_html += f'<li><a href="{bugreport.id}/">{bugreport.title}</a></li>'
#         bugs_html += '</ul>'
#         return HttpResponse(bugs_html)

# class FeatureListView(ListView):
#     model = FeatureRequest

#     def get(self, request, *args, **kwargs):
#         features = self.get_queryset()
#         features_html = '<h1>Список гениальных идей</h1><ul>'
#         for featurerequest in features:
#             features_html += f'<li><a href="{featurerequest.id}/">{featurerequest.title}</a></li>'
#         features_html += '</ul>'
#         return HttpResponse(features_html)

# from django.views.generic import DetailView

# class BugDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bugreport_id'

#     def get(self, request, *args, **kwargs):
#         bugreports = self.get_object()
#         response_html = f'<h1>{bugreports.title}</h1><p>{bugreports.description}</p><p>{bugreports.status}</p><p>{bugreports.priority}</p><p>{bugreports.task}</p><p>{bugreports.project}</p>'
#         return HttpResponse(response_html)
    
# class FeatureDetailView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'featurerequest_id'

#     def get(self, request, *args, **kwargs):
#         featurerequests = self.get_object()
#         response_html = f'<h1>{featurerequests.title}</h1><p>{featurerequests.description}</p><p>{featurerequests.status}</p><p>{featurerequests.priority}</p><p>{featurerequests.task}</p><p>{featurerequests.project}</p>'
#         return HttpResponse(response_html)

quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список багов</h1>
            <!-- Ссылка на создание нового проекта -->
    <p><a href="{% url 'quality_control:create_bugreport' %}">Заявить о баге</a></p>
    <ul>
        {% for bugreport in bug_list %}
            <li><a href="{% url 'quality_control:bugreport_detail' bugreport.id %}">{{ bugreport.title }}</a></li>
            
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Заявить о новом баге</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bugreport_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление бага</h1>
    <p>Вы уверены, что хотите удалить баг "{{ bugreport.name }}"?</p>

    <form action="{% url 'quality_control:delete_bugreport' bugreport.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bugreport_detail' bugreport.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bugreport_detail.html
{% extends 'base/base.html' %}


{% block content %}
    <h1>{{ bugreport_detail.title }}</h1>
    <p>{{ bugreport_detail.description }}</p>
    <p>{{ bugreport_detail.status }}</p>
    <p>{{ bugreport_detail.priority }}</p>
    <a href="{% url 'quality_control:update_bugreport' bugreport_id=bugreport_detail.id %}">Изменить баг</a>
    <p><a href="{% url 'quality_control:delete_bugreport' bugreport_id=bugreport_detail.id %}" onclick="return confirm('Вы уверены, что хотите удалить эту задачу?');">Удалить баг</a></p>

{% endblock %}

quality_control/templates/quality_control/bugreport_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение бага: {{ bugreport.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список идей</h1>
    <p><a href="{% url 'quality_control:create_featurerequest' %}">Предложить идею</a></p>
    <ul>
        {% for featurerequest in feature_list %}
            <li><a href="{% url 'quality_control:featurerequest_detail' featurerequest.id %}">{{ featurerequest.title }}</a></li>
            
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Предложить идею</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/featurerequest_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление идеи</h1>
    <p>Вы уверены, что хотите удалить идею "{{ featurerequest.name }}"?</p>

    <form action="{% url 'quality_control:delete_featurerequest' featurerequest.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:featurerequest_detail' featurerequest.id %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/featurerequest_detail.html
{% extends 'base/base.html' %}


{% block content %}
    <h1>{{ featurerequest_detail.title }}</h1>
    <p>{{ featurerequest_detail.description }}</p>
    <p>{{ featurerequest_detail.status }}</p>
    <p>{{ featurerequest_detail.priority }}</p>
    <a href="{% url 'quality_control:update_featurerequest' featurerequest_id=featurerequest_detail.id %}">Изменить идею</a>
    <p><a href="{% url 'quality_control:delete_featurerequest' featurerequest_id=featurerequest_detail.id %}" onclick="return confirm('Вы уверены, что хотите удалить эту задачу?');">Удалить идею</a></p>

{% endblock %}

quality_control/templates/quality_control/featurerequest_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение идеи: {{ featurerequest.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Система контроля качества</h1>
        <a href="{% url 'quality_control:bug_list' %}">Список багов</p>
        <a href="{% url 'quality_control:feature_list' %}">Список идей</a>
{% endblock %}